"""create users table 

Revision ID: 910b6ae51141
Revises: e32e729160db
Create Date: 2024-09-01 14:00:02.310706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910b6ae51141'
down_revision = 'e32e729160db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
